const USER_USERNAME = import.meta.env.VITE_USER_USERNAME
const USER_PASSWORD = import.meta.env.VITE_USER_PASSWORD
const ADMIN_USERNAME = import.meta.env.VITE_ADMIN_USERNAME
const ADMIN_PASSWORD = import.meta.env.VITE_ADMIN_PASSWORD
const OWNER_USERNAME = import.meta.env.VITE_OWNER_USERNAME
const OWNER_PASSWORD = import.meta.env.VITE_OWNER_PASSWORD

export {
    USER_USERNAME,
    USER_PASSWORD,
    ADMIN_USERNAME,
    ADMIN_PASSWORD,
    OWNER_USERNAME,
    OWNER_PASSWORD
}